
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Jun 22 01:38:23 CST 2019
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int menos = 15;
  public static final int sobreescribir = 70;
  public static final int llavecierra = 5;
  public static final int menor = 20;
  public static final int mod = 52;
  public static final int parder = 13;
  public static final int identificador = 7;
  public static final int menosu = 19;
  public static final int punto = 74;
  public static final int nulo = 75;
  public static final int booleano = 35;
  public static final int decremento = 37;
  public static final int leerarchivo = 72;
  public static final int character = 9;
  public static final int importar = 66;
  public static final int tochar = 80;
  public static final int aumento = 36;
  public static final int div = 17;
  public static final int mas = 14;
  public static final int cadena = 30;
  public static final int dospuntos = 42;
  public static final int menorigual = 23;
  public static final int mientras = 39;
  public static final int abstracto = 65;
  public static final int imprimir = 40;
  public static final int superior = 81;
  public static final int privado = 61;
  public static final int imprimirconlinea = 44;
  public static final int sino = 45;
  public static final int toint = 79;
  public static final int decimal = 29;
  public static final int caso = 50;
  public static final int interrogacion = 41;
  public static final int corcheteder = 57;
  public static final int igualacion = 27;
  public static final int or = 25;
  public static final int caracter = 3;
  public static final int mayorigual = 22;
  public static final int nuevo = 58;
  public static final int retorno = 71;
  public static final int estatico = 63;
  public static final int parizq = 12;
  public static final int extender = 68;
  public static final int llaveabre = 4;
  public static final int seleccion = 49;
  public static final int casteo = 55;
  public static final int rfinal = 64;
  public static final int rvoid = 59;
  public static final int protegido = 62;
  public static final int cadenaString = 32;
  public static final int and = 26;
  public static final int mayor = 21;
  public static final int escribirarchivo = 83;
  public static final int xor = 18;
  public static final int printtabla = 11;
  public static final int EOF = 0;
  public static final int leer = 82;
  public static final int este = 73;
  public static final int falso = 34;
  public static final int numero = 2;
  public static final int publico = 60;
  public static final int arroba = 69;
  public static final int potencia = 53;
  public static final int verdadero = 33;
  public static final int corcheteizq = 56;
  public static final int error = 1;
  public static final int caststr = 77;
  public static final int continuar = 47;
  public static final int diferente = 24;
  public static final int si = 43;
  public static final int entero = 8;
  public static final int pcoma = 10;
  public static final int quiebre = 38;
  public static final int hacer = 48;
  public static final int defecto = 51;
  public static final int por = 16;
  public static final int para = 46;
  public static final int graficar = 76;
  public static final int coma = 54;
  public static final int not = 28;
  public static final int doble = 31;
  public static final int igual = 6;
  public static final int todouble = 78;
  public static final int clase = 67;
}

